### ISSUE TITLE
Issue with interface name (transport name in Windows) when locale is not English

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence-dhcp-forwarder#12]
When the installer runs in a language other than English, the output of getmac will return "N/A" in Transport Name which will have the service fail to start because that's not the right interface name

In order to workaround, you can launch the installer while the default Windows locale is set to English.

We should use FindAllDev of the golang pcap library instead of getmac

**Comment by nqb** [comment]
With the command `getmac /v` in `cmd` you could get the device ID in the form of : `\Device\Tcpip_{DEVICE_ID}`.

In `DHCP-Forwarder.toml`, you could use:

```toml
ListeningDevice = "\\Device\\NPF_{DEVICE_ID}"
```

**Comment by julsemaan** [comment]
This should be addressed via https://github.com/inverse-inc/packetfence-dhcp-forwarder/pull/16

Because it listens on all interfaces now and because @jrouzierinverse reworked the interface selection to be in Golang vs using getmac
