### ISSUE TITLE
Upgrade to npcap

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence-dhcp-forwarder#15]
We need to upgrade to use npcap since winpcap is no longer being updated.

https://www.winpcap.org/news.htm

https://npcap.com/

https://github.com/nmap/npcap/blob/master/LICENSE

We need to look into a possible licensing issue if we include it with the dhcp-forwarder in the installer.

**Comment by julsemaan** [comment]
That was addressed in https://github.com/inverse-inc/packetfence-dhcp-forwarder/pull/16
