### ISSUE TITLE
GNU Linux version of DHCP-Forwarder is missing

### ISSUE THREAD

**Issue by tlaurion** [inverse-inc/packetfence-dhcp-forwarder#8]
Only DHCP-Forwarder would be required:
- verify which approach is better: dynamic compilation, dynamic runtime, seperated versions for Linux/Windows for event-logging (event logs vs syslogs)
- check for libpcap library availibility
- validate how gopacket sees interfaces

**Comment by julsemaan** [comment]
@dwlfrth just did this I think and it works on Linux now

Let's close this when we have confirmation it works in production
